### ISSUE TITLE
Not copying anypb correctly?

### ISSUE THREAD

**Issue by artificial-james** [mennanov/fieldmask-utils#21]
I don't believe StructToStruct is handling anypb correctly.  Take a look at the attached patch:
[any_existing.patch.txt](https://github.com/mennanov/fieldmask-utils/files/7108039/any_existing.patch.txt)

It appears to be copying other fields.  Notice the ExtraUser Role field has changed even though it isn't included in the mask.

Edit:  Also, the ExtraUser Name field should be unchanged (since it isn't included in the mask), but is changing to "username".

**Comment by mennanov** [comment]
This is clearly a bug. Thanks for reporting.
Now fixed.
