### ISSUE TITLE
CamelCase func in docs is now deprecated

### ISSUE THREAD

**Issue by alee792** [mennanov/fieldmask-utils#23]
When building a project following the examples, I receive the following notice:
```        google.golang.org/protobuf/protoc-gen-go/generator: cannot find module providing package google.golang.org/protobuf/protoc-gen-go/generator```

Unfortunately, the new package does not export [their GoCamelCase func](https://github.com/protocolbuffers/protobuf-go/blob/fb30439f551a7e79e413e7b4f5f4dfb58e117d73/internal/strs/strings.go).

Not sure how you prefer to address this, but I do think the docs should be updated to an alternative, if one exists.

**Comment by mennanov** [comment]
I've updated the docs.

Thanks for reporting!
