### ISSUE TITLE
*int64 panic 

### ISSUE THREAD

**Issue by leeming87v5** [mennanov/fieldmask-utils#33]
*int64 field got panic by StructToMap()，stack as below
<img width="784" alt="image" src="https://user-images.githubusercontent.com/4251271/212857227-7050e572-ef30-4eb9-9e32-5fe7769323ff.png">
<img width="473" alt="image" src="https://user-images.githubusercontent.com/4251271/212857404-a1098bf2-f3b1-454f-a065-0e98e7363326.png">
<img width="612" alt="image" src="https://user-images.githubusercontent.com/4251271/212857682-529549fa-4ace-41b6-961f-d680e04bfa35.png">

example:
```golang
import (
	msku "github.com/mennanov/fieldmask-utils"
)

type example struct {
	P2Int64  *int64
	WhatEver string
}

func willPanic() {
	var (
		i         int64 = 666
		updateMap       = make(map[string]interface{})
	)

	mask, _ := msku.MaskFromPaths(
		[]string{"P2Int64", "WhatEver"},
		func(s string) string { return s },
	)

	// panic here
	_ = msku.StructToMap(
		mask,
		&example{
			P2Int64:  &i,
			WhatEver: "what ever",
		},
		updateMap,
	)
}

```

**Comment by mennanov** [comment]
Thanks for reporting. I'm working on a fix. It will be ready in a few days.

**Comment by mennanov** [comment]
Please, try https://github.com/mennanov/fieldmask-utils/pull/34 and see if it works for you

**Comment by mennanov** [comment]
This should now be fixed in the new major release: https://github.com/mennanov/fieldmask-utils/releases/tag/v1.0.0
