### ISSUE TITLE
What I set is NOT what I get ???

### ISSUE THREAD

**Issue by leeming87v5** [mennanov/fieldmask-utils#36]
```go
package main

import (
	"fmt"

	msku "github.com/mennanov/fieldmask-utils"
)

func main() {
	var (
		err  error
		mask msku.Mask
	)

	if mask, err = msku.MaskFromPaths(
		[]string{"a.b.c"},
		func(s string) string { return s },
	); err != nil {
		panic(err)
	}

	if _, ok := mask.Get("a.b.c"); ok {
                 // I expected this would work
		fmt.Println("That's Good! As Expcted!")
	} else {
                // but I got this instead.
                // Why ???
		fmt.Println("Oops! Suprise!")
	}
}

```

**Comment by rMaxiQp** [comment]
Here is the [implementation](https://github.com/mennanov/fieldmask-utils/blob/master/mask.go#L159). Since it's a nested mask, I don't think `mask.Get("a.b.c")` would work here...

**Comment by mennanov** [comment]
> Here is the [implementation](https://github.com/mennanov/fieldmask-utils/blob/master/mask.go#L159). Since it's a nested mask, I don't think `mask.Get("a.b.c")` would work here...

right, the mask is nested so it works as expected
