### ISSUE TITLE
whether add Option SrcTag() for copy from src tag

### ISSUE THREAD

**Issue by zhuliquan** [mennanov/fieldmask-utils#37]
https://github.com/mennanov/fieldmask-utils/blob/f9573a9a16fd68cd4ab04fca7d1b16dadc7e346a/copy.go#L74C4-L74C14

now  mask.Filter use the FiledName of object, However, path also input json_tag, I hope this package can add SrcTag Option for this scene

**Comment by zhuliquan** [comment]
I add this feature in PR https://github.com/mennanov/fieldmask-utils/pull/38

**Comment by mennanov** [comment]
Thanks for contributing!
